# Generated by Django 6.1 on 2026-08-16 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='joined_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
